// Library of automotive terms, slang, and concepts for negotiation logic

export const automotiveTerms = {
  financing: [
    "APR",
    "residual value",
    "money factor",
    "lease term",
    "down payment",
    "balloon payment",
    "depreciation",
    "gap insurance",
    "buyout price",
    "capitalized cost",
    "disposition fee",
    "acquisition fee",
    "early termination fee",
  ],
  dealerTactics: [
    "hidden fees",
    "marked-up interest rate",
    "add-ons",
    "extended warranty",
    "paint protection",
    "VIN etching",
    "advertising fees",
    "destination charges",
    "market adjustment",
  ],
  negotiationPhrases: [
    "out-the-door price",
    "OTD",
    "monthly payment",
    "trade-in value",
    "rebates",
    "incentives",
    "cash back",
    "dealer holdback",
    "invoice price",
    "MSRP",
    "sticker price",
    "factory-to-dealer incentives",
  ],
  makesAndModels: [
    "Toyota Camry",
    "Honda Accord",
    "Ford F-150",
    "Chevrolet Silverado",
    "Tesla Model 3",
    "BMW 3 Series",
    "Mercedes-Benz C-Class",
    "Audi A4",
    "Jeep Wrangler",
    "Subaru Outback",
  ],
};